### ISSUE TITLE
Headers required by SSE?

### ISSUE THREAD

**Issue by menjaraz** [mtharrison/susie#10]
Why do you include just **one** _header_ (ie: `content-type`) but not also the **other remaining** _headers_ ( `cache-control` and `connection` I mean) usually found in other SSE library?

**Comment by mtharrison** [comment]
Can you point me in the direction of another library so I can take a look?

The spec doesn't say anything about `Connection` header. On cache headers it says:

> User agents should ignore HTTP cache headers in the response, never caching event sources.
