### ISSUE TITLE
How to create a chatroom ?

### ISSUE THREAD

**Issue by vdeturckheim** [mtharrison/susie#8]
Hi,

I like this plugin a lot, however I wanted to ask for advice regarding the creation of a multi-rooms chat with SUSIE.

I assume I would need the following setup:
- `GET /room/{roomId}` to subscribe to the room. 
- `POST /room/{roomId}` to write into the room

How do I make the actions executed in the POST handler get sent to the GET one ? And also, is there a solution to do this even if I have multiple instance of server that would get access to a redis or mongo base?

thanks a lot!

**Comment by mtharrison** [comment]
Yes. Server-sent events are just one way, so you could use a common stream to provide the messages via susie.

To send a message, you could make a normal POST request and in the handler for that request, just write a message into the same stream so all subscribers get it.

If you're using multiple node, yes you need to have a way to sync them all up. Redis pub/sub pattern would work.

**Comment by vdeturckheim** [comment]
@mtharrison thanks for your answer ! 
Would you accept a PR with an example of a simple chat ?

**Comment by mtharrison** [comment]
Sure thing, that would be great!

**Comment by vdeturckheim** [comment]
Probably this week-end then ^^

**Comment by menjaraz** [comment]
@vdeturckheim Can't wait for the good news

**Comment by vdeturckheim** [comment]
@menjaraz coming its way ^^ I had a busier week-end than expected and Xmas is around the corner, but that's definitely on my todo list.

**Comment by mtharrison** [comment]
I made a quick example of a chat app using susie and React, you may be interested: https://github.com/mtharrison/susie-react-chat

**Comment by vdeturckheim** [comment]
@mtharrison thanks, sorry for the no-delivery :/
